### ISSUE TITLE
How to remove some information from recordings?

### ISSUE THREAD

**Issue by tabrez96** [ScaleLeap/jest-polly#129]
Thank you so much for this amazing package, configuring pollyjs with jest was very simple with this. I just have a small question, I need to remove some data like `startedDateTime` which gets changed for each recording and manually set `_id` for each entry. Basically, I need to prevent unnecessary diff when a new recording is made.

**Comment by moltar** [comment]
@tabrez96 glad you like it.

Check it out here: https://github.com/ScaleLeap/amazon-advertising-api-sdk/blob/master/test/polly.js

And then see how it is wired up into jest: https://github.com/ScaleLeap/amazon-advertising-api-sdk/blob/master/jest.config.js

This is for a global polly, but you can do the same inside individual test files, if you only need it in a small scope of tests.

**Comment by tabrez96** [comment]
Perfect! works as expected. Thanks a lot!
