### ISSUE TITLE
Incompatible with Jest v27 (changed to circus by default)

### ISSUE THREAD

**Issue by jeking3** [ScaleLeap/jest-polly#228]
In config.ts, in JestPollyConfigService, we have:

```
  private factory(): PollyConfigWithSecrets {
    const recordingsRoot = path.dirname(global.jasmine.testPath)
```

When I run the code with Jest v27:

```Cannot read property 'testPath' of undefined```

Jest v27 uses the circus test engine.  I had to put this into my `jest.config.js` file to work around it:

```
  ...
  testRunner: "jest-jasmine2"
  ...
```

**Comment by moltar** [comment]
Hm, yeah, this is a bug for sure. But not sure how to solve this yet.

The solution relied on reaching into undocumented internals `global.jasmine.testPath`. But this is no longer supported by circus runner.

The `setup-polly-jest` package that we use under the hood [now requires using a custom `testEnvironment` to make this work](https://github.com/gribnoysup/setup-polly-jest#supported-test-runners), which also feel kind of like a cludge.

So the only solution I can think of at the moment is to create a version of the `testEnvironment` implementation as well, which then sets the required `global` with the `testPath` value. Here's an [example](https://stackoverflow.com/a/63002088/1566758) and [Jest docs](https://jestjs.io/docs/configuration#testenvironment-string).

---

Another issue from a similar implementation to watch for: https://github.com/spotify/polly-jest-presets/issues/30

**Comment by nguyentoanit** [comment]
@jeking3 : Could you give it a try with latest version?

**Comment by moltar** [comment]
It works with latest Jest, closing.
